"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import JSZip from "jszip";
import {
  components,
  categoryOrder,
  categoryColors,
  resolveDeps,
  type ComponentCategory,
  type RegistryComponent,
} from "@/data/registry";

const README_TEMPLATE = (names: string[]) => `# Anex UI — Custom Component Bundle

Components included: ${names.join(", ")}

## Setup

### 1. Install peer dependencies
\`\`\`bash
npm install react@^19 react-dom@^19 clsx tailwind-merge
\`\`\`

### 2. Add the path alias (tsconfig.json / vite.config.ts)
\`\`\`json
{
  "compilerOptions": {
    "paths": { "@/*": ["./src/*"] }
  }
}
\`\`\`

### 3. Place files in your project
Copy the \`components/\`, \`lib/\`, and \`tokens/\` folders into your \`src/\` directory:
\`\`\`
src/
  components/   ← component folders from this zip
  lib/
    cn.ts
  tokens/
    index.css
    themes.css
\`\`\`

### 4. Import the design tokens once at your app root
\`\`\`ts
import "@/tokens/index.css";
import "@/tokens/themes.css";
\`\`\`

### 5. Set a theme on the html element
\`\`\`html
<html data-theme="dark">
\`\`\`

### 6. Use a component
\`\`\`tsx
import Button from "@/components/Button/Button";

<Button variant="solid">Hello</Button>
\`\`\`

---
Generated by [Anex UI Builder](https://anexui.dev/builder)
`;

export default function BuilderPage() {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [downloading, setDownloading] = useState(false);
  const [done, setDone] = useState(false);

  const resolved = resolveDeps(selected);

  const toggle = useCallback((id: string) => {
    setDone(false);
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  const toggleCategory = useCallback((cat: ComponentCategory) => {
    setDone(false);
    const catIds = components.filter((c) => c.category === cat).map((c) => c.id);
    setSelected((prev) => {
      const next = new Set(prev);
      const allSelected = catIds.every((id) => prev.has(id));
      catIds.forEach((id) => (allSelected ? next.delete(id) : next.add(id)));
      return next;
    });
  }, []);

  const selectAll = () => {
    setDone(false);
    setSelected(new Set(components.map((c) => c.id)));
  };

  const clearAll = () => {
    setDone(false);
    setSelected(new Set());
  };

  const download = async () => {
    if (resolved.size === 0) return;
    setDownloading(true);
    setDone(false);

    try {
      const zip = new JSZip();
      const toInclude = components.filter((c) => resolved.has(c.id));

      // Fetch and add each component's files
      await Promise.all(
        toInclude.map(async (comp: RegistryComponent) => {
          await Promise.all(
            comp.files.map(async (file) => {
              const url = `/registry/components/${comp.categorySlug}/${comp.folderName}/${file}`;
              const res = await fetch(url);
              if (!res.ok) return;
              let text = await res.text();
              // Rewrite internal lib import paths to match zip structure
              text = text.replace(/from ["']\.\.\/\.\.\/\.\.\/lib\/cn["']/g, 'from "@/lib/cn"');
              text = text.replace(/from ["']\.\.\/\.\.\/lib\/cn["']/g, 'from "@/lib/cn"');
              zip.file(`components/${comp.folderName}/${file}`, text);
            })
          );
        })
      );

      // Fetch shared lib
      const cnRes = await fetch("/registry/lib/cn.ts");
      if (cnRes.ok) zip.file("lib/cn.ts", await cnRes.text());

      // Fetch tokens
      const tokensRes = await fetch("/registry/tokens/index.css");
      if (tokensRes.ok) zip.file("tokens/index.css", await tokensRes.text());

      const themesRes = await fetch("/registry/tokens/themes.css");
      if (themesRes.ok) zip.file("tokens/themes.css", await themesRes.text());

      // Generate README
      zip.file("README.md", README_TEMPLATE(toInclude.map((c) => c.label)));

      // Trigger download
      const blob = await zip.generateAsync({ type: "blob" });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = "anexui-components.zip";
      a.click();
      URL.revokeObjectURL(a.href);
      setDone(true);
    } catch (e) {
      console.error(e);
    } finally {
      setDownloading(false);
    }
  };

  const byCategory = categoryOrder.map((cat) => ({
    cat,
    items: components.filter((c) => c.category === cat),
  }));

  const autoAdded = [...resolved].filter(
    (id) => !selected.has(id) && components.find((c) => c.id === id)
  );

  return (
    <>
      {/* Page header */}
      <div className="border-b border-white/8 bg-[#080808]/80 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3 text-sm">
            <Link href="/" className="text-white/40 hover:text-white/70 transition-colors">Anex UI</Link>
            <span className="text-white/20">/</span>
            <span className="text-white/70">Component Builder</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={clearAll}
              className="text-xs text-white/40 hover:text-white/70 transition-colors"
            >
              Clear all
            </button>
            <button
              onClick={selectAll}
              className="text-xs text-white/40 hover:text-white/70 transition-colors"
            >
              Select all
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-10 flex gap-10 items-start">
        {/* Left — picker */}
        <div className="flex-1 min-w-0 space-y-8">
          <div>
            <h1 className="text-2xl font-bold text-white mb-2">Pick your components</h1>
            <p className="text-white/50 text-sm">
              Select only what you need. Download a zip with source files, design tokens, and a setup README — no bloat.
            </p>
          </div>

          {byCategory.map(({ cat, items }) => {
            const catIds = items.map((c) => c.id);
            const selectedCount = catIds.filter((id) => resolved.has(id)).length;
            const allChecked = catIds.every((id) => selected.has(id));
            const someChecked = catIds.some((id) => selected.has(id)) && !allChecked;
            const colors = categoryColors[cat];

            return (
              <section key={cat}>
                {/* Category header */}
                <div className="flex items-center gap-3 mb-3">
                  <button
                    onClick={() => toggleCategory(cat)}
                    className={`flex items-center gap-2 text-xs font-semibold uppercase tracking-wider px-2.5 py-1 rounded-full border transition-colors ${
                      allChecked
                        ? colors
                        : someChecked
                        ? colors + " opacity-60"
                        : "text-white/30 border-white/10 bg-transparent"
                    }`}
                  >
                    <span
                      className={`w-3.5 h-3.5 rounded border flex items-center justify-center flex-shrink-0 ${
                        allChecked
                          ? "bg-current border-current"
                          : someChecked
                          ? "border-current"
                          : "border-white/20"
                      }`}
                    >
                      {allChecked && (
                        <svg viewBox="0 0 10 8" fill="none" className="w-2 h-2">
                          <path d="M1 4l2.5 2.5L9 1" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      )}
                      {someChecked && <span className="w-1.5 h-0.5 bg-current rounded-full" />}
                    </span>
                    {cat}
                  </button>
                  {selectedCount > 0 && (
                    <span className="text-xs text-white/30">{selectedCount}/{items.length}</span>
                  )}
                </div>

                {/* Component grid */}
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                  {items.map((comp) => {
                    const isSelected = selected.has(comp.id);
                    const isAutoAdded = !isSelected && resolved.has(comp.id);

                    return (
                      <button
                        key={comp.id}
                        onClick={() => toggle(comp.id)}
                        className={`group flex items-center gap-2.5 px-3 py-2.5 rounded-xl border text-sm text-left transition-all ${
                          isSelected
                            ? "bg-violet-600/20 border-violet-500/40 text-white"
                            : isAutoAdded
                            ? "bg-white/[0.04] border-white/15 text-white/60"
                            : "bg-[#111] border-white/8 text-white/50 hover:border-white/20 hover:text-white/80"
                        }`}
                      >
                        <span
                          className={`w-4 h-4 rounded border flex-shrink-0 flex items-center justify-center transition-colors ${
                            isSelected
                              ? "bg-violet-500 border-violet-500"
                              : isAutoAdded
                              ? "border-white/30"
                              : "border-white/20"
                          }`}
                        >
                          {(isSelected || isAutoAdded) && (
                            <svg viewBox="0 0 10 8" fill="none" className="w-2.5 h-2.5">
                              <path d="M1 4l2.5 2.5L9 1" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          )}
                        </span>
                        <span className="truncate">{comp.label}</span>
                        {isAutoAdded && (
                          <span className="ml-auto text-[10px] text-white/30 flex-shrink-0">auto</span>
                        )}
                      </button>
                    );
                  })}
                </div>
              </section>
            );
          })}
        </div>

        {/* Right — download panel */}
        <div className="w-72 shrink-0 sticky top-24">
          <div className="bg-[#111] border border-white/10 rounded-2xl p-5 space-y-5">
            {/* Count */}
            <div>
              <p className="text-xs text-white/40 uppercase tracking-wider mb-1">Selected</p>
              <p className="text-3xl font-bold text-white">
                {resolved.size}
                <span className="text-base font-normal text-white/30 ml-1">/ {components.length}</span>
              </p>
            </div>

            {/* Auto-added notice */}
            {autoAdded.length > 0 && (
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl px-3 py-2.5">
                <p className="text-xs text-amber-400 font-medium mb-1">Auto-included</p>
                <p className="text-xs text-amber-400/70">
                  {autoAdded.map((id) => components.find((c) => c.id === id)?.label).join(", ")} — required by your selection.
                </p>
              </div>
            )}

            {/* What's in the zip */}
            {resolved.size > 0 && (
              <div className="space-y-1">
                <p className="text-xs text-white/40 uppercase tracking-wider mb-2">Bundle includes</p>
                <div className="max-h-48 overflow-y-auto space-y-1 pr-1">
                  {[...resolved].map((id) => {
                    const comp = components.find((c) => c.id === id)!;
                    return (
                      <div key={id} className="flex items-center gap-2 text-xs text-white/60">
                        <span className="w-1 h-1 rounded-full bg-violet-400 flex-shrink-0" />
                        {comp.label}
                      </div>
                    );
                  })}
                </div>
                <div className="pt-2 border-t border-white/8 space-y-1">
                  <div className="flex items-center gap-2 text-xs text-white/30">
                    <span className="w-1 h-1 rounded-full bg-white/20 flex-shrink-0" />
                    lib/cn.ts
                  </div>
                  <div className="flex items-center gap-2 text-xs text-white/30">
                    <span className="w-1 h-1 rounded-full bg-white/20 flex-shrink-0" />
                    tokens/index.css + themes.css
                  </div>
                  <div className="flex items-center gap-2 text-xs text-white/30">
                    <span className="w-1 h-1 rounded-full bg-white/20 flex-shrink-0" />
                    README.md
                  </div>
                </div>
              </div>
            )}

            {/* Download button */}
            <button
              onClick={download}
              disabled={resolved.size === 0 || downloading}
              className={`w-full py-3 rounded-xl font-medium text-sm transition-all ${
                resolved.size === 0
                  ? "bg-white/5 text-white/20 cursor-not-allowed"
                  : done
                  ? "bg-emerald-600 text-white"
                  : "bg-violet-600 hover:bg-violet-500 text-white"
              }`}
            >
              {downloading
                ? "Building zip…"
                : done
                ? "Downloaded ✓"
                : resolved.size === 0
                ? "Select components"
                : `Download ${resolved.size} component${resolved.size !== 1 ? "s" : ""}`}
            </button>

            {done && (
              <p className="text-xs text-white/40 text-center">
                Check the README.md inside the zip for setup instructions.
              </p>
            )}

            {/* Footer links */}
            <div className="pt-1 border-t border-white/8 flex items-center justify-between text-xs text-white/30">
              <Link href="/docs/getting-started" className="hover:text-white/60 transition-colors">
                Full install guide →
              </Link>
              <Link href="/docs/components" className="hover:text-white/60 transition-colors">
                Browse docs →
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
